# Generated by Django 4.0.5 on 2022-07-21 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otchet', '0002_profile_delete_peoples'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='balanсe',
            field=models.PositiveIntegerField(default=0, verbose_name='Баланс'),
        ),
        migrations.AddField(
            model_name='profile',
            name='room_number',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Номер комнаты'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='День рождения'),
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата')),
                ('payment_method', models.CharField(choices=[('Перевод', 'Перевод на карту'), ('Наличные', 'Наличные')], default='Перевод', max_length=50, verbose_name='Способ оплаты')),
                ('summa', models.PositiveIntegerField(default=0, verbose_name='Сумма оплаты')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='otchet.profile')),
            ],
        ),
    ]
