# Generated by Django 4.0.6 on 2022-07-28 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otchet', '0003_profile_balanсe_profile_room_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Комната', 'verbose_name_plural': 'Комнаты'},
        ),
        migrations.AlterModelOptions(
            name='spendingadmin',
            options={'verbose_name': 'Расходы админа', 'verbose_name_plural': 'Расходы админа'},
        ),
        migrations.AlterModelOptions(
            name='spendingboss',
            options={'verbose_name': 'Расходы хозяина', 'verbose_name_plural': 'Расходы хозяина'},
        ),
        migrations.AlterModelOptions(
            name='spendinghostel',
            options={'verbose_name': 'Расходы дома', 'verbose_name_plural': 'Расходы дома'},
        ),
        migrations.RemoveField(
            model_name='payments',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='payments',
            name='method',
            field=models.CharField(choices=[('card', 'Перевод на карту'), ('cash', 'Наличные')], default='card', max_length=50, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='otchet.profile'),
        ),
    ]
