# Generated by Django 4.0.5 on 2022-08-24 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otchet', '0005_remove_profile_room_number_profile_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payments',
            options={'verbose_name': 'Платеж', 'verbose_name_plural': 'Платежи'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Постоялец', 'verbose_name_plural': 'Постояльцы'},
        ),
    ]
