# Generated by Django 4.0.5 on 2022-08-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otchet', '0006_alter_payments_options_alter_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='method',
            field=models.CharField(choices=[('CARD', 'Перевод на карту'), ('CASH', 'Наличные')], default='CARD', max_length=50, verbose_name='Способ оплаты'),
        ),
    ]
