# Generated by Django 4.0.5 on 2022-08-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otchet', '0007_alter_payments_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='method',
            field=models.CharField(choices=[('card', 'Перевод на карту'), ('cash', 'Наличные')], default='card', max_length=50, verbose_name='Способ оплаты'),
        ),
    ]
