# Generated by Django 4.0.5 on 2022-08-29 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otchet', '0009_remove_profile_user_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='', max_length=11, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='otchet.profile', verbose_name='Имя'),
        ),
    ]
