# Generated by Django 4.0.5 on 2022-08-29 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otchet', '0010_profile_phone_number_alter_payments_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_of_birth',
        ),
    ]
