# Generated by Django 4.0.5 on 2022-08-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otchet', '0011_remove_profile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='balanсe',
            field=models.IntegerField(default=0, verbose_name='Баланс'),
        ),
    ]
