# Generated by Django 4.0.5 on 2022-09-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otchet', '0012_alter_profile_balanсe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, verbose_name='Дата')),
                ('event', models.CharField(max_length=200, verbose_name='Мероприятие')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='79876543412', max_length=11, verbose_name='Номер телефона'),
        ),
    ]
