# Generated by Django 4.0.5 on 2022-09-02 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otchet', '0013_events_alter_profile_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refunds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата')),
                ('method', models.CharField(choices=[('card', 'Перевод на карту'), ('cash', 'Наличные')], default='card', max_length=50, verbose_name='Способ оплаты')),
                ('summa', models.PositiveIntegerField(default=0, verbose_name='Сумма возврата')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='otchet.profile', verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Возврат',
                'verbose_name_plural': 'Возвраты',
            },
        ),
    ]
