# Generated by Django 4.0.5 on 2022-09-02 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otchet', '0014_refunds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='balanсe',
        ),
    ]
