# Generated by Django 4.0.5 on 2022-09-10 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otchet', '0016_alter_payments_options_alter_payments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата'),
        ),
    ]
