# Generated by Django 4.0.5 on 2022-09-10 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otchet', '0019_alter_departures_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departures',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='otchet.profile', verbose_name='Имя'),
        ),
    ]
