# Generated by Django 4.1.1 on 2022-09-12 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otchet', '0026_alter_profile_options_alter_room_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='events',
            table='events',
        ),
    ]
