# Generated by Django 4.1.1 on 2022-09-12 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otchet', '0027_alter_events_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='departures',
            table='departures',
        ),
        migrations.AlterModelTable(
            name='payments',
            table='payments',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
        migrations.AlterModelTable(
            name='refunds',
            table='refunds',
        ),
        migrations.AlterModelTable(
            name='room',
            table='room',
        ),
        migrations.AlterModelTable(
            name='spendingadmin',
            table='adminspending',
        ),
        migrations.AlterModelTable(
            name='spendingboss',
            table='bossspending',
        ),
        migrations.AlterModelTable(
            name='spendinghostel',
            table='hostelspending',
        ),
    ]
