# Generated by Django 4.1.1 on 2022-09-12 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otchet', '0028_alter_departures_table_alter_payments_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'get_latest_by': ['date'], 'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
    ]
