# Generated by Django 4.1.1 on 2022-09-12 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otchet', '0029_alter_events_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
    ]
