# Generated by Django 4.1.1 on 2022-09-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otchet', '0030_alter_events_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nikola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, null=True)),
                ('last_name', models.CharField(default='', max_length=30, null=True)),
                ('favorite', models.ManyToManyField(blank=True, to='otchet.nikola')),
            ],
            options={
                'verbose_name': 'Никола',
                'verbose_name_plural': 'Николы',
            },
        ),
    ]
