# Generated by Django 4.1.1 on 2022-09-12 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otchet', '0031_nikola'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nikola',
        ),
    ]
