# Generated by Django 4.1.1 on 2022-09-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otchet', '0034_payments_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='name',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
