# Generated by Django 4.1.1 on 2022-09-14 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otchet', '0035_payments_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='name',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='otchet.profile', verbose_name='Имя'),
        ),
    ]
