# Generated by Django 4.1.1 on 2022-09-19 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otchet', '0039_alter_payments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='refunds',
            name='name',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='refunds',
            name='room',
            field=models.CharField(max_length=3, null=True, verbose_name='Номер комнаты'),
        ),
        migrations.AlterField(
            model_name='refunds',
            name='summa',
            field=models.PositiveIntegerField(default=0, verbose_name='Сумма оплаты'),
        ),
        migrations.AlterField(
            model_name='refunds',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='otchet.profile', verbose_name='Профиль'),
        ),
        migrations.AlterModelTable(
            name='payments',
            table=None,
        ),
    ]
