# Generated by Django 4.1.1 on 2022-09-19 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otchet', '0040_refunds_name_refunds_room_alter_refunds_summa_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='payments',
            table='payments',
        ),
    ]
