# Generated by Django 4.1.1 on 2022-09-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otchet', '0041_alter_payments_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='summa',
            field=models.IntegerField(default=0, verbose_name='Сумма оплаты'),
        ),
        migrations.AlterField(
            model_name='refunds',
            name='summa',
            field=models.IntegerField(default=0, verbose_name='Сумма оплаты'),
        ),
    ]
