# Generated by Django 4.1.1 on 2022-09-21 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otchet', '0042_alter_payments_summa_alter_refunds_summa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ['-date'], 'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='spendingadmin',
            options={'ordering': ['-date'], 'verbose_name': 'Расходы админа', 'verbose_name_plural': 'Расходы админа'},
        ),
        migrations.AlterModelOptions(
            name='spendingboss',
            options={'ordering': ['-date'], 'verbose_name': 'Расходы хозяина', 'verbose_name_plural': 'Расходы хозяина'},
        ),
        migrations.AlterModelOptions(
            name='spendinghostel',
            options={'ordering': ['-date'], 'verbose_name': 'Расходы дома', 'verbose_name_plural': 'Расходы дома'},
        ),
    ]
