# Generated by Django 4.1.1 on 2022-09-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otchet', '0043_alter_events_options_alter_spendingadmin_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departures',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='refunds',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Дата'),
        ),
    ]
