# Generated by Django 4.1.1 on 2022-09-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otchet', '0046_alter_spendingadmin_date_alter_spendingboss_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата'),
        ),
    ]
