# Generated by Django 4.1.1 on 2022-09-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otchet', '0047_alter_events_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='79876543412', max_length=12, verbose_name='Номер телефона'),
        ),
    ]
