# Generated by Django 4.1.1 on 2022-09-29 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otchet', '0048_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-number'], 'verbose_name': 'Комната', 'verbose_name_plural': 'Комнаты'},
        ),
    ]
