# Generated by Django 4.1.1 on 2022-09-29 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otchet', '0049_alter_room_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['room'], 'verbose_name': 'Постоялец', 'verbose_name_plural': 'Постояльцы'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['number'], 'verbose_name': 'Комната', 'verbose_name_plural': 'Комнаты'},
        ),
    ]
