# Generated by Django 4.1.2 on 2022-10-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otchet', '0050_alter_profile_options_alter_room_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, verbose_name='Имя')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='Email')),
            ],
        ),
    ]
