# Generated by Django 4.1.2 on 2022-10-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otchet', '0051_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_done',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата')),
                ('event', models.CharField(max_length=200, verbose_name='Мероприятие')),
            ],
            options={
                'verbose_name': 'Мероприятие проведено',
                'verbose_name_plural': 'Мероприятия проведены',
                'db_table': 'events_done',
                'ordering': ['-date'],
            },
        ),
        migrations.RenameModel(
            old_name='Events',
            new_name='Event_plan',
        ),
    ]
